DellyShopCoreWebAppAdminPanel/DellyShopCoreWebApp/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DellyShop.Domain.Models;
using DellyShop.Domain.ViewModels;
using DellyShop.Repos;
using DellyShopCoreWebApp.Models;
using DellyShopCoreWebAppAdminPanel.Models;
using Microsoft.AspNetCore.Mvc;

namespace DellyShopCoreWebAppAdminPanel.Controllers
{
    public class OrderController : Controller
    {
        private RepositoryService _repo;
        public OrderController(RepositoryService repo)
        {
            _repo = repo;
        }
        public IActionResult Index(OrderViewModel viewModel)
        {
            List<Order> orders = _repo.Orders.GetAllOrders(viewModel.SelectedCustomer);
            List<Customer> customers = _repo.Customers.GetCustomers();

            viewModel.Orders = orders;
            viewModel.Customers = customers;

            return View(viewModel);
        }
        public IActionResult Update(int Id)
        {
            Order order = _repo.Orders.GetOrderById(Id);

            OrderEditViewModel viewModel = new OrderEditViewModel()
            {
                Id = order.Id,
                Description = order.Description,
                Customer = order.Customer,
                OrderState = order.OrderState,
                ShippingCostPrice = order.ShippingCostPrice,
                TotalPrice = order.TotalPrice,
                ProductOrderMany = order.ProductOrderMany
            };

            return View("Edit", viewModel);
        }
        [HttpPost]
        public IActionResult Update(OrderEditViewModel viewModel)
        {
            
            var result = _repo.Orders.Update(viewModel);

            if (result == "OK")
            {
                return View("Info", new InfoViewModel( "Order Id =" + viewModel.Id +  "is Edited"));
            }

            return View("Error", new ErrorViewModel("Couldn't edit Order, please try again."));
        }
        public IActionResult Delete(int id)
        {
            var result = _repo.Orders.Delete(id);

            if (result == "OK")
            {
                return View("Info", new InfoViewModel("Order Id =" + id + " is deleted"));
            }

            return View("Error", new ErrorViewModel("Couldn't delete Order, please try again."));
        }
    }
}

DellyShopCoreWebAppAdminPanel/DellyShopCoreWebApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DellyShop.Domain.Models;
using DellyShop.Domain.ViewModels;
using DellyShop.Repos;
using DellyShopCoreWebApp.Models;
using DellyShopCoreWebAppAdminPanel.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DellyShopCoreWebAppAdminPanel.Controllers
{
    public class UserController : Controller
    {
        private RepositoryService _repo;
        private readonly UserManager<ApplicationUser> _userManager;
        public UserController(RepositoryService repo, UserManager<ApplicationUser> userManager)
        {
            _repo = repo;
            _userManager = userManager;
        }
        public IActionResult Index(UserViewModel viewModel)
        {
            var users = _repo.Users.GetAllUsers(viewModel.SelectedUser);

            viewModel.Users = users;

            return View(viewModel);
        }
        //public IActionResult Create()
        //{
        //    UserCreateOrEditViewModel viewModel = new UserCreateOrEditViewModel()
        //    {
        //        Action = "/Account/Register",
        //        Button = "Create",
        //        Title = "User Create",
        //        LockoutEnabled = true
        //    };

        //    return View("CreateOrEdit", viewModel);
        //}

        //[HttpPost]
        //public IActionResult Create(UserCreateOrEditViewModel viewModel)
        //{
        //    var result = _repo.Users.Create(viewModel);

        //    if (result == "OK")
        //    {
        //        return View("Info", new InfoViewModel(viewModel.FullName + " is added."));
        //    }

        //    return View("Error", new ErrorViewModel("The values you submitted are not suitable, please try again."));
        //}

        public IActionResult UpdateUser(string Id)
        {
            var result = _repo.Users.GetAllUsers(Id);

            UserCreateOrEditViewModel viewModel = new UserCreateOrEditViewModel()
            {
                Action = "/User/UpdateUser",
                Button = "Update",
                Title = "User Update",
                UserId = result.FirstOrDefault().Id,
                FirstName = result.FirstOrDefault().FirstName,
                LastName = result.FirstOrDefault().LastName,
                Email = result.FirstOrDefault().Email,
                PhoneNumber = result.FirstOrDefault().PhoneNumber,
                Password = result.FirstOrDefault().PasswordHash,
                LockoutEnabled = result.FirstOrDefault().LockoutEnabled
            };

            return View("CreateOrEdit", viewModel);
        }

        [HttpPost]
        public IActionResult UpdateUser(UserCreateOrEditViewModel viewModel)
        {
            var result = _repo.Users.Update(viewModel);

            if (result == "OK")
            {
                return View("Info", new InfoViewModel(viewModel.FullName + " is Updated."));
            }

            return View("Error", new ErrorViewModel("The values you submitted are not suitable, please try again."));
        }
        public IActionResult Delete(string Id)
        {
            var user = _repo.Users.GetAllUsers(Id);
            var result = _repo.Users.Delete(user.FirstOrDefault());

            if (result == "OK")
            {
                return View("Info", new InfoViewModel(user.FirstOrDefault().FullName + " is Deleted."));
            }

            return View("Error", new ErrorViewModel("Couldn't delete user, please try again."));
        }
    }
}

DellyShopCoreWebAppAdminPanel/DellyShopCoreWebApp/Views/Order/Edit.cshtml
@model DellyShop.Domain.ViewModels.OrderEditViewModel
@using DellyShop.Domain.Enums

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    <h2 class="text-center bg-info text-gray-dark"> <b>Order Edit</b> for Customer Name = @Model.Customer.Name </h2>

<div class="row">
    <div class="col-md-12">
        <form action="/Product/Edit" method="post">
            <input type="hidden" name="UserId" value="@Model.Id" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group js-categoryId col-lg-4">
                <label asp-for="ProductOrderMany" class="control-label"></label>
                <select asp-for="SelectedProduct" name="SelectedCategory" class="form-control">
                    <option selected="selected" value="0">Products</option>
                    @foreach (var product in Model.ProductOrderMany)
                    {
                        <option value="@product.Id">@product.Product.Name</option>
                    }
                </select>
                <span asp-validation-for="ProductOrderMany" class="text-danger"></span>
            </div>

            <div class="form-group col-lg-4">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" required />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-4">
                <label asp-for="ShippingCostPrice" class="control-label"></label>
                <input asp-for="ShippingCostPrice" class="form-control" required />
                <span asp-validation-for="ShippingCostPrice" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-4">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" required />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>

            <div class="form-group col-lg-4">
                <label asp-for="OrderState" class="control-label"></label>
                <select asp-for="OrderState" value="1" class="form-control" asp-items="@Html.GetEnumSelectList(typeof(OrderState))"></select>
                <span asp-validation-for="OrderState" class="text-danger"></span>
            </div>
            
            <div class="form-group text-danger">
                <input asp-for="@Model.IsActive" type="checkbox" id="isActive" /> <label> Is Active ? </label>
            </div>

            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-success js-button-doubleclick" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="text text-danger">Return to User List!</a>
</div>
@section scripts{
    <script src="~/lib/jquery/jquery.min.js"></script>
}

DellyShopCoreWebAppAdminPanel/DellyShopCoreWebApp/Views/Order/Index.cshtml
@model DellyShop.Domain.ViewModels.OrderViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center bg-info text-gray-dark">Orders</h1>


<div class="row">
    <div class="col-lg-12">
        <form asp-action="Index" method="get">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group col-lg-4">
                <label asp-for="Customers" class="control-label"></label>
                <select asp-for="SelectedCustomer" name="SelectedCustomer" class="form-control">
                    <option selected="selected" value="0">All Customer</option>
                    @foreach (var customer in Model.Customers)
                    {
                        <option value="@customer.Id">@customer.Name @customer.Surname</option>
                    }
                </select>
                <span asp-validation-for="Customers" class="text-danger"></span>
            </div>

            <div class="col-lg-12">
                <div class="form-group">
                    <input type="submit" value="Ara" class="btn btn-info" />
                </div>
            </div>
        </form>
        @*<div class="col-lg-12">

                <a class="btn btn-success float-lg-right" asp-controller="User" asp-action="Create"><b>Add New User</b></a>

            </div>*@
    </div>
</div>
<div class="row">
    <div class="col-xs-12 table-responsive">
        <table class="table table-striped disabled" id="example">
            <thead>
                <tr>
                    @*<th>Product Id <i class="fas fa-filter"></i></th>*@
                    <th>OrderId <i class="fas fa-filter"></i></th>
                    <th>Order State <i class="fas fa-filter"></i></th>
                    <th>Customer <i class="fas fa-filter"></i></th>
                    <th>OtderCount <i class="fas fa-filter"></i></th>
                    <th>TotalPrice <i class="fas fa-filter"></i></th>
                    <th>Description <i class="fas fa-filter"></i></th>
                    @*<th>Products <i class="fas fa-filter"></i></th>*@
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var order in Model.Orders)
                {
                    <tr>
                        <td>@order.Id</td>
                        <td>@order.OrderState</td>
                        <td>@order.Customer.Name  @order.Customer.Surname</td>
                        <td>@order.OrderCount</td>
                        <td>@order.TotalPrice</td>
                        <td>@order.Description</td>
                        <td class="float-right">
                            | @Html.ActionLink("Edit", "Update", "Order", new { id = order.Id }) |
                            <span class="btn btn-danger btn-sm" id="textBlack">@Html.ActionLink("Delete", "Delete", "Order", new { id = order.Id })</span>
                        </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
    <!-- /.col -->
</div>

@section Scripts {

    <script>

        $(document).ready(function () {
            $('#example').DataTable({
                "dom": '<"top"i>rt<"bottom"flp><"clear">',
                "dom": '<"wrapper"flipt>',
                "dom": '<lf<t>ip>'
            });
        });


    </script>

}