DellyShopCoreWebAppAdminPanel/DellyShopCoreWebApp/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DellyShop.Domain.ViewModels;
using DellyShop.Repos;
using DellyShopCoreWebApp.Models;
using DellyShopCoreWebAppAdminPanel.Models;
using Microsoft.AspNetCore.Mvc;

namespace DellyShopCoreWebAppAdminPanel.Controllers
{
    public class CommentController : Controller
    {
        private RepositoryService _repo;
        public CommentController(RepositoryService repo)
        {
            _repo = repo;
        }
        public IActionResult Index(CommentIndexViewModel viewModel)
        {
            var product = _repo.Products.GetProducts(0);
            var comment = _repo.Comments.GetCommentsByProductId(viewModel.SelectedProduct);
            viewModel.Comments = comment;
            viewModel.Products = product;

            return View(viewModel);
        }
        public IActionResult Delete(int id)
        {
            var result = _repo.Comments.Delete(id);

            if (result == "OK")
            {
                return View("Info", new InfoViewModel("Comment is deleted id = " + id));
            }

            return View("Error", new ErrorViewModel("Could not delete comment , please try again."));
        }
    }
}

DellyShopCoreWebAppAdminPanel/DellyShopCoreWebApp/Views/Comment/Index.cshtml
@model DellyShop.Domain.ViewModels.CommentIndexViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1 class="text-center bg-info text-gray-dark"> Comments </h1>


<div class="row">
    <div class="col-lg-12">
        <form asp-action="Index" method="get">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group col-lg-4">
                <label asp-for="Products" class="control-label"></label>
                <select asp-for="SelectedProduct" name="SelectedProduct" class="form-control">
                    <option selected="selected" value="0">All Product</option>
                    @foreach (var product in Model.Products)
                    {
                        <option value="@product.Id">@product.Name</option>
                    }
                </select>
                <span asp-validation-for="Products" class="text-danger"></span>
            </div>

            <div class="col-lg-12">
                <div class="form-group">
                    <input type="submit" value="Ara" class="btn btn-info" />
                </div>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 table-responsive">
        <table class="table table-striped disabled" id="example">
            <thead>
                <tr>
                    <th>CommentId <i class="fas fa-filter"></i></th>
                    <th>Text <i class="fas fa-filter"></i></th>
                    <th>CreatedOn <i class="fas fa-filter"></i></th>
                    <th>Commented Product <i class="fas fa-filter"></i></th>
                    <th>Is Active <i class="fas fa-filter"></i></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var comment in Model.Comments)
                {
                    <tr>
                        <td>@comment.Id</td>
                        <td>@comment.Text</td>
                        <td>@comment.CreatedOn</td>
                        <td>@comment.Product.Name</td>
                        <td>@comment.IsActive</td>
                        <td class="float-right">
                            <span class="btn btn-danger btn-sm" id="textBlack">@Html.ActionLink("Delete", "Delete", "Comment", new { id = comment.Id })</span>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- /.col -->
</div>

@section Scripts {

    <script>

        $(document).ready(function () {
            $('#example').DataTable({
                "dom": '<"top"i>rt<"bottom"flp><"clear">',
                "dom": '<"wrapper"flipt>',
                "dom": '<lf<t>ip>'
            });
        });


    </script>

}